variables:
  - group: 'MVISION_GROUP'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
     echo Intiating MVISION tempalte auditing...
     echo "Input variables MVISION_User:"$MVISION_USERNAME "CLOUD_SERVICE_PROVIDER:"$CLOUD_SERVICE_PROVIDER "ENVIRONMENT:"$ENVIRONMENT
     git log HEAD -1 --name-only --pretty="format:" > changes.txt
     cat changes.txt
     egrep -i '.json|.tf|.yml|.yaml' changes.txt > changes_latest.txt
     cat changes_latest.txt
     data=$(cat changes_latest.txt | while read line; do echo $line; done)
     data=$(echo $data  | tr ' ' ',')
     #ls $(Build.Repository.LocalPath)
     docker run -v $(Build.Repository.LocalPath):/data mcafeemvision/shift-left-aws:1.2.0 $data $MVISION_USERNAME $MAPPED_ENV_VAR "/data" $CLOUD_SERVICE_PROVIDER $ENVIRONMENT
  env:
    MAPPED_ENV_VAR: $(MVISION_PASSWORD)
  displayName: 'MVISION template auditing..'
